In [1]:
import random
import time
import numpy as np

In [11]:
x=np.random.rand(1000000000)

In [7]:
start=time.time()
mean=sum(x)/len(x)
print(time.time()-start)

141.3812267780304


In [6]:
import random
import time
import numpy as np
x=np.random.rand(1000000000)
start= time.time()
mean=np.mean(x)
print(time.time() - start)

1.9597651958465576


In [9]:
x=np.array([1,2,3,4,5])
print(x)
type(x)

[1 2 3 4 5]


numpy.ndarray

In [13]:
#shape function
print(x)
print("x has dimentions :" , x.shape)
print("x is a object of type :",type(x))
print("The elements of are of type :",x.dtype)

[1 2 3 4 5]
x has dimentions : (5,)
x is a object of type : <class 'numpy.ndarray'>
The elements of are of type : int32


In [14]:
x=np.array(['subhram','patel'])
print(x)
print("x has dimentions :" , x.shape)
print("x is a object of type :",type(x))
print("The elements of are of type :",x.dtype)

['subhram' 'patel']
x has dimentions : (2,)
x is a object of type : <class 'numpy.ndarray'>
The elements of are of type : <U7


In [19]:
x=np.array([[1,2],[3,4],[5,6]])
print("x has dimentions :" , x.shape)
print("x is a object of type :",type(x))
print("The elements of are of type :",x.dtype)

x has dimentions : (3, 2)
x is a object of type : <class 'numpy.ndarray'>
The elements of are of type : int32


In [16]:
x=np.array([1.2,2.4,3.6,4.1,5.3],dtype =np.int32)
print(x)
print(type(x),x.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'> int32


In [18]:
x=np.array([1,2,3,4,5])
np.save('my_array',x)