In [1]:
import numpy as np

In [42]:
#np.array(dimentions)[creating array]
aa=np.array([1,2,3],dtype=float)
print(aa,aa.dtype)

[1. 2. 3.] float64


In [55]:
#np.zeros(dimentions)
a=np.zeros(3)
b=np.zeros((3,2))
c=np.zeros((2,3,4))

print(a,"\n\n",b,"\n\n",c)
print("\n\n",a.shape,b.shape,c.shape)

[0. 0. 0.] 

 [[0. 0.]
 [0. 0.]
 [0. 0.]] 

 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


 (3,) (3, 2) (2, 3, 4)


In [10]:
#np.full(dimention,value)
d=np.full((3,2),2)
print(d)

[[2 2]
 [2 2]
 [2 2]]


In [12]:
#np.random.rand(dimentions)[array of random floate between 0-1]
e=np.random.rand(3,5)
print(e)

[[0.53944345 0.48626496 0.48718512 0.77995133 0.08230221]
 [0.95069937 0.17624194 0.88646466 0.62969834 0.9775802 ]
 [0.94848301 0.94419986 0.899233   0.84780355 0.7450597 ]]


In [15]:
#np.ones(dimentions)
f=np.ones((3,4,5))
print(f)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [38]:
#np.eye(dimentions)[IDENTIY MATRIX]
g=np.eye(4)
print(g)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [61]:
#np.diag([diagonal elements])
h=np.diag([10,20,30,40,50,60,70])
print(h)

[[10  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0]
 [ 0  0 30  0  0  0  0]
 [ 0  0  0 40  0  0  0]
 [ 0  0  0  0 50  0  0]
 [ 0  0  0  0  0 60  0]
 [ 0  0  0  0  0  0 70]]


In [56]:
#saving and loading
i=np.save("new_array",e)
j=np.load("new_array.npy")
print(j)

[[0.53944345 0.48626496 0.48718512 0.77995133 0.08230221]
 [0.95069937 0.17624194 0.88646466 0.62969834 0.9775802 ]
 [0.94848301 0.94419986 0.899233   0.84780355 0.7450597 ]]


In [65]:
#np.arrange(range like for loop)
k=np.arange(0,20,2)
print(k)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
#np.